- set_fact:
    config_path: "{{home_path}}/.config/yandex-disk"
  
- set_fact:
    yandex_auth: "{{ lookup('keepass', {'tag':'yandex-disk'}, search='custom') }}"
    default_mount_point: "{{home_path}}/.yandex-disk"
    token_path: "{{ config_path }}/passwd"

- name: Make dir
  file:
    path: "{{ config_path }}"
    state: "directory"
    owner: "{{ user }}"
    group: "{{ user }}"


# https://yandex.com/support/disk/cli-clients.xml#cli-install
- name: Key
  get_url:
    url: "https://repo.yandex.ru/yandex-disk/YANDEX-DISK-KEY.GPG"
    dest: "/etc/apt/keyrings/yandex-disk.asc"

- name: Repo
  apt_repository: repo='deb [signed-by=/etc/apt/keyrings/yandex-disk.asc] http://repo.yandex.ru/yandex-disk/deb/ stable main' filename="yandex-disk"

- name: apt-get install yandex-disk
  apt: name=yandex-disk state=latest

- name: check config
  file:
    path: "{{ config_path }}/config.cfg"
    state: file
  failed_when: false
  register: check_yd_config

- name: ask mount point
  pause:
    prompt: "Enter YD mount point ('{{ default_mount_point }}' by default)"
  register: mount_point
  changed_when: false
  when: check_yd_config.state == 'absent'

- name: config
  template:
    src: config.cfg.j2
    dest: "{{ config_path }}/config.cfg"
    backup: true
  become: true
  become_user: "{{ user }}"
  when: check_yd_config.state == 'absent'

# https://github.com/slytomcat/yandex-disk-indicator
#- name: Yandex Disk Indicator - add ppa
#  apt_repository: repo="ppa:slytomcat/ppa" codename="{{ codename }}" filename=yd-tools

#- name: install Yandex Disk Indicator
#  apt: name=yd-tools update_cache=yes
 
- name: Check token exists
  file:
    path: "{{ token_path }}"
    state: file
  failed_when: false
  register: check_yd_token

- name: Create token
  command: yandex-disk token --password={{yandex_auth.password}} {{yandex_auth.username}} "{{ token_path }}"
  become: true
  become_user: "{{user}}"
  when: check_yd_token.state == 'absent'

