# https://wiki.archlinux.org/index.php/Davfs2#Storing_credentials

- name: apt-get install davfs2
  apt: name="davfs2" state=latest update_cache=yes

- name: configure
  lineinfile: path=/etc/davfs2/davfs2.conf regexp="^#use_locks" line="use_locks 0"
