- name: Install packages
  apt: 
    pkg: ['python3-dev', 'python3-pip']
    state: latest

- name: Install pykeepass
  shell: pip install pykeepass
  become: true
  become_user: "{{user}}"
  changed_when: false