# https://medium.com/risan/upgrade-your-ssh-key-to-ed25519-c6e8d60d3c54
# https://security.stackexchange.com/questions/143442/what-are-ssh-keygen-best-practices
# https://wiki.archlinux.org/index.php/SSH_keys

- set_fact:
    ssh_keys: "{{ lookup('keepass', {'tag':'ssh-key'}, search='custom') }}"

- name: Copy public keys
  copy:
    dest: "{{home_path}}/.ssh/{{item.title}}.pub"
    content: "{{ item.fields.public }}"
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0600
    backup: true
  with_items: "{{ssh_keys}}"
  
- name: Copy private keys
  copy:
    dest: "{{home_path}}/.ssh/{{item.title}}"
    content: "{{ item.fields.private }}"
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0600
    backup: true
  with_items: "{{ssh_keys}}"

- name: Check ed25519 key exists
  file:
    path: "{{home_path}}/.ssh/id_ed25519"
    state: file
  failed_when: false
  register: check_id_ed25519

- name: Check rsa key exists
  file:
    path: "{{home_path}}/.ssh/id_rsa"
    state: file
  failed_when: false
  register: check_id_rsa

- name: ask email
  pause:
    prompt: "Enter SSH key email"
  register: ssh_key_email
  changed_when: false
  when: (check_id_ed25519.state == 'absent') or (check_id_rsa.state == 'absent')

- name: Create ed25519 key
  command: "ssh-keygen -o -a 100 -t ed25519 -f ~{{ user }}/.ssh/id_ed25519 -N \"\" -C \"{{ ssh_key_email.user_input }} - {{lookup('pipe', 'date +%Y-%m-%d')}}\""
  become: true
  become_user: "{{user}}"
  when: check_id_ed25519.state == 'absent'

- name: Create rsa key
  command: "ssh-keygen -o -a 100 -t rsa -b 4096 -f ~{{ user }}/.ssh/id_rsa -N \"\" -C \"{{ ssh_key_email.user_input }} - {{lookup('pipe', 'date +%Y-%m-%d')}}\""
  become: true
  become_user: "{{user}}"
  when: check_id_rsa.state == 'absent'