- name: apt-get install keychain
  apt: name=keychain state=latest

- name: Find public keys
  find:
    paths: "{{home_path}}/.ssh"
    patterns: '*.pub'
    recurse: yes
  register: get_public_keys

- name: Agent autostart
  lineinfile:
    path: "{{home_path}}/.bashrc"
    regexp: " {{item.path | basename | splitext | first}}[)]" # https://stackoverflow.com/a/32656118/2041969
    line: "eval $(keychain --eval {{item.path | basename | splitext | first}})" # eval $(keychain --eval id_ed25519)
  with_items: "{{ get_public_keys.files }}"
